USE [BIBLIO_DB]
GO

/****** Object:  Table [dbo].[COURANT_LITTERAIRE]    Script Date: 03/08/2021 15:09:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COURANT_LITTERAIRE](
	[IDCOURANT] [int] NOT NULL,
	[NOMC] [nvarchar](50) NULL,
	[IDGENRE] [int] NULL,
 CONSTRAINT [PK_COURANT_LITTERAIRE] PRIMARY KEY CLUSTERED 
(
	[IDCOURANT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[COURANT_LITTERAIRE]  WITH CHECK ADD  CONSTRAINT [FK_COURANT_LITTERAIRE_GENRE] FOREIGN KEY([IDGENRE])
REFERENCES [dbo].[GENRE] ([IDGENRE])
GO

ALTER TABLE [dbo].[COURANT_LITTERAIRE] CHECK CONSTRAINT [FK_COURANT_LITTERAIRE_GENRE]
GO

