USE [BIBLIO_DB]
GO

/****** Object:  Table [dbo].[EDITION]    Script Date: 03/08/2021 15:09:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EDITION](
	[IDMAISON] [int] IDENTITY(1,1) NOT NULL,
	[NOM] [nvarchar](50) NULL,
	[DESCRIPTION] [varchar](max) NULL,
 CONSTRAINT [PK_MAISON_EDITION] PRIMARY KEY CLUSTERED 
(
	[IDMAISON] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

