USE [BIBLIO_DB]
GO

/****** Object:  Table [dbo].[GENRE]    Script Date: 03/08/2021 15:09:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GENRE](
	[IDGENRE] [int] IDENTITY(1,1) NOT NULL,
	[NOMG] [nvarchar](50) NULL,
 CONSTRAINT [PK_GENRE] PRIMARY KEY CLUSTERED 
(
	[IDGENRE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

