USE [BIBLIO_DB]
GO

/****** Object:  Table [dbo].[LIVRE]    Script Date: 03/08/2021 15:10:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LIVRE](
	[IDLIVRE] [int] IDENTITY(1,1) NOT NULL,
	[TITRE] [nvarchar](50) NULL,
	[IDAUTEUR] [int] NULL,
	[IDGENRE] [int] NULL,
	[IDCOURANT] [int] NULL,
	[IDMAISON] [int] NULL,
	[ISBN] [varchar](50) NULL,
	[ANNEE] [date] NULL,
	[IMAGE_LIVRE] [varchar](50) NULL,
	[URL_IMAGE_LIVRE] [varchar](50) NULL,
 CONSTRAINT [PK_LIVRE] PRIMARY KEY CLUSTERED 
(
	[IDLIVRE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[LIVRE]  WITH CHECK ADD  CONSTRAINT [FK_LIVRE_AUTEUR] FOREIGN KEY([IDAUTEUR])
REFERENCES [dbo].[AUTEUR] ([IDAUTEUR])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[LIVRE] CHECK CONSTRAINT [FK_LIVRE_AUTEUR]
GO

ALTER TABLE [dbo].[LIVRE]  WITH CHECK ADD  CONSTRAINT [FK_LIVRE_COURANT_LITTERAIRE] FOREIGN KEY([IDCOURANT])
REFERENCES [dbo].[COURANT_LITTERAIRE] ([IDCOURANT])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[LIVRE] CHECK CONSTRAINT [FK_LIVRE_COURANT_LITTERAIRE]
GO

ALTER TABLE [dbo].[LIVRE]  WITH CHECK ADD  CONSTRAINT [FK_LIVRE_GENRE] FOREIGN KEY([IDGENRE])
REFERENCES [dbo].[GENRE] ([IDGENRE])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[LIVRE] CHECK CONSTRAINT [FK_LIVRE_GENRE]
GO

ALTER TABLE [dbo].[LIVRE]  WITH CHECK ADD  CONSTRAINT [FK_LIVRE_MAISON_EDITION] FOREIGN KEY([IDMAISON])
REFERENCES [dbo].[EDITION] ([IDMAISON])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[LIVRE] CHECK CONSTRAINT [FK_LIVRE_MAISON_EDITION]
GO

